version: '3.8'

services:
  meu-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    container_name: api-gateway

  meu-auth:
    build: ./auth-service
    container_name: api-auth

  meu-patient:
    build: ./patient-service
    depends_on:
      - meu-banco-dados
    deploy:
      replicas: 3

 
  meu-banco-dados:
    image: postgres:15-alpine
    container_name: database-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_super_secreta
      POSTGRES_DB: clinica_db
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: