version: '3.8'

services:
  # API Gateway (A porta de entrada)
  meu-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000" # O usuário só acessa essa porta
    container_name: api-gateway

  # Serviço de Paciente
  meu-patient:
    build: ./patient-service
    # O computador físico não acessa mais essa caixa, só o Gateway acessa ela pela rede interna.
    container_name: api-patient

  # Serviço de Autenticação 
  meu-auth:
    build: ./auth-service
    # Também apagamos o "ports" aqui pelo mesmo motivo da segurança.
    container_name: api-auth